version: '3'

services:
  mysql:
    container_name: "mysql"
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - spring-net

  liquibase:
    container_name: "liquibase"
    image: liquibase.jar
    build:
      context: "/mnt/c/Users/Daniel_Canillas/Documents/Training Project/liquibase"
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    networks:
      - spring-net
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    depends_on:
      - mysql

  discovery-service:
    container_name: "discovery-service"
    image: discovery-service.jar
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - "8761:8761"
    networks:
      - spring-net
    environment:
      EUREKA_HOST: discovery-service
      EUREKA_PORT: 8761

  product-service:
    container_name: "product-service"
    image: product-service.jar
    build:
      context: "/mnt/c/Users/Daniel_Canillas/Documents/Training Project/productservice"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    networks:
      - spring-net
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      EUREKA_HOST: discovery-service
      EUREKA_PORT: 8761
    depends_on:
      - mysql
      - liquibase

  recommendation-service:
    container_name: "recommendation-service"
    image: recommendation-service.jar
    build:
      context: "/mnt/c/Users/Daniel_Canillas/Documents/Training Project/recommendationservice"
      dockerfile: "Dockerfile"
    ports:
      - "9090:9090"
    networks:
      - spring-net
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      EUREKA_HOST: discovery-service
      EUREKA_PORT: 8761
    depends_on:
      - mysql
      - liquibase

  gateway-service:
    container_name: "gateway-service"
    image: gateway-service.jar
    build:
      context: "/mnt/c/Users/Daniel_Canillas/Documents/Training Project/gatewayservice"
      dockerfile: "Dockerfile"
    ports:
      - "9000:9000"
    networks:
      - spring-net
    environment:
      EUREKA_HOST: discovery-service
      EUREKA_PORT: 8761
    depends_on:
      - mysql
      - liquibase
      - product-service
      - recommendation-service

networks:
  spring-net:
    external: true